version: '3.9'
services:
  postgres:
    image: postgres
    container_name: pg_monitor-service
    network_mode: host
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/$USER/docker_pg_data:/var/lib/postgresql/data

  monitor-service:
    container_name: monitor-service
    build: 
      context: ./
    env_file: 
      - .development.env
    network_mode: host
    depends_on: 
      - postgres